[tool.ruff]
line-length = 110
indent-width = 4
target-version = "py313"

# Enable rules to cover flake8, isort, pylint, pydocstyle, etc.
lint.select = [
  "E",    # pycodestyle errors (flake8)
  "F",    # pyflakes (flake8)
  "W",    # pycodestyle warnings
  "I",    # isort (import sorting)
  "NPY",  # NumPy-specific rules
  "N",    # pep8-naming
  "D",    # pydocstyle (docstrings)
  "PL",   # pylint checks
  "RUF",  # Ruff-specific improvements
]

# Optionally ignore some rules you find too strict
lint.ignore = [
  "D100",     # undocumented-public-module
  "D101",     # undocumented-public-class
  "D104",     # undocumented-public-package
  "E501",     # line-too-long
  "E741",     # ambiguous-variable-name
  "N801",     # invalid-class-name
  "N802",     # invalid-function-name
  "N803",     # invalid-argument-name
  "N806",     # non-lowercase-variable-in-function
  "N813",     # camelcase-imported-as-lowercase
  "N999",     # invalid-module-name
  "PLR0911",  # too-many-return-statements
  "PLR0912",  # too-many-branches
  "PLR0913",  # too-many-arguments
  "PLR0915",  # too-many-statements
  "PLR2004",  # magic-value-comparison
  "PLW2901",  # redefined-loop-name
  "RUF010",   # explicit-f-string-type-conversion
]

# Exclude these paths from checks (customize as needed)
exclude = [
  "__pycache__",
]

# Allow automatic fixing for all rules
fix = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
# Enable formatting similar to Black
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
skip-magic-trailing-comma = false

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SlowQuant"
version = "0.1.0"
description = "A quantum chemistry package"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "BSD 3"}

authors = [
    {name = "Erik Kjellgren, Karl Michael Ziems"}
]

dependencies = [
    "networkx>=3.0", # Only supporting latest major
    "numba>=0.60", # NumPy 2.0 support
    "numpy>=2.0", # Only supporting latest major
    "pyscf>=2.4", # Older versions have Mole deepcopy issues
    "scipy>=1.13", # NumPy 2.0 support
    "sympy>=1.9", # Python 3.10 support
    "qiskit==2.1.1", # Known to work
    "qiskit-aer==0.17.2", # Known to work
    "qiskit-ibm-provider==0.11.0", # Known to work
    "qiskit-ibm-runtime==0.41.1", # Known to work
    "qiskit-nature==0.7.2", # Known to work
]

[project.urls]
Homepage = "https://github.com/erikkjellgren/SlowQuant"

[tool.setuptools]
package-dir = {"" = "slowquant"}

[tool.setuptools.packages.find]
where = ["slowquant"]
